### ISSUE TITLE
Generates Error on Platfrom.IO

### ISSUE THREAD

**Issue by danielschlingmeier** [luisllamasbinaburo/Arduino-Interpolation#10]
Maybe similar/same issue like on the previous issue, but different IDE: Visual Studio Code + Platform.OI says:

.pio/libdeps/wemos_d1_mini32/InterpolationLib/src/InterpolationLib.cpp:10:114: error: default argument given for parameter 5 of 'static double Interpolation::Step(double*, double*, int, double, double)' [-fpermissive]
 double Interpolation::Step(double xValues[], double yValues[], int numValues, double pointX, double threshold = 1)
                                                                                                                  ^
In file included from .pio/libdeps/wemos_d1_mini32/InterpolationLib/src/InterpolationLib.cpp:8:
.pio/libdeps/wemos_d1_mini32/InterpolationLib/src/InterpolationLib.h:66:16: note: previous specification in 'static double Interpolation::Step(double*, double*, int, double, double)' here
  static double Step(double xValues[], double yValues[], int numValues, double pointX, double threshold = 1);
                ^~~~
.pio/libdeps/wemos_d1_mini32/InterpolationLib/src/InterpolationLib.cpp:24:112: error: default argument given for parameter 5 of 'static double Interpolation::Linear(double*, double*, int, double, bool)' [-fpermissive]
 double Interpolation::Linear(double xValues[], double yValues[], int numValues, double pointX, bool trim = true)
                                                                                                                ^
In file included from .pio/libdeps/wemos_d1_mini32/InterpolationLib/src/InterpolationLib.cpp:8:
.pio/libdeps/wemos_d1_mini32/InterpolationLib/src/InterpolationLib.h:70:16: note: previous specification in 'static double Interpolation::Linear(double*, double*, int, double, bool)' here
  static double Linear(double xValues[], double yValues[], int numValues, double pointX, bool trim = true);
                ^~~~~~
.pio/libdeps/wemos_d1_mini32/InterpolationLib/src/InterpolationLib.cpp:56:116: error: default argument given for parameter 5 of 'static double Interpolation::SmoothStep(double*, double*, int, double, bool)' [-fpermissive]
 double Interpolation::SmoothStep(double xValues[], double yValues[], int numValues, double pointX, bool trim = true)
                                                                                                                    ^
In file included from .pio/libdeps/wemos_d1_mini32/InterpolationLib/src/InterpolationLib.cpp:8:
.pio/libdeps/wemos_d1_mini32/InterpolationLib/src/InterpolationLib.h:72:16: note: previous specification in 'static double Interpolation::SmoothStep(double*, double*, int, double, bool)' here
  static double SmoothStep(double xValues[], double yValues[], int numValues, double pointX, bool trim = true);
                ^~~~~~~~~~
.pio/libdeps/wemos_d1_mini32/InterpolationLib/src/InterpolationLib.cpp:75:119: error: default argument given for parameter 5 of 'static double Interpolation::CatmullSpline(double*, double*, int, double, bool)' [-fpermissive]
 double Interpolation::CatmullSpline(double xValues[], double yValues[], int numValues, double pointX, bool trim = true)
                                                                                                                       ^
In file included from .pio/libdeps/wemos_d1_mini32/InterpolationLib/src/InterpolationLib.cpp:8:
.pio/libdeps/wemos_d1_mini32/InterpolationLib/src/InterpolationLib.h:73:16: note: previous specification in 'static double Interpolation::CatmullSpline(double*, double*, int, double, bool)' here
  static double CatmullSpline(double xValues[], double yValues[], int numValues, double pointX, bool trim = true);
                ^~~~~~~~~~~~~
.pio/libdeps/wemos_d1_mini32/InterpolationLib/src/InterpolationLib.cpp:131:123: error: default argument given for parameter 5 of 'static double Interpolation::ConstrainedSpline(double*, double*, int, double, bool)' [-fpermissive]
 double Interpolation::ConstrainedSpline(double xValues[], double yValues[], int numValues, double pointX, bool trim = true)
                                                                                                                           ^
In file included from .pio/libdeps/wemos_d1_mini32/InterpolationLib/src/InterpolationLib.cpp:8:
.pio/libdeps/wemos_d1_mini32/InterpolationLib/src/InterpolationLib.h:74:16: note: previous specification in 'static double Interpolation::ConstrainedSpline(double*, double*, int, double, bool)' here
  static double ConstrainedSpline(double xValues[], double yValues[], int numValues, double pointX, bool trim = true);
                ^~~~~~~~~~~~~~~~~
*** [.pio\build\wemos_d1_mini32\lib03f\InterpolationLib\InterpolationLib.cpp.o] Error 1

I personally don't understand why the functions are defined as "static double". Also the default parameter seems to be TRUE, which is not mentioned in the Readme file -> should be added

Best regards
Daniel

**Comment by luisllamasbinaburo** [comment]
Update library to 1.0.2 
- 1.0.1 solves the compilation problems. But, due to a typo in library.properties, new version was not published in Arduino repos

So i created this new release. It's should work to you now.

Thanks for the report
