### ISSUE TITLE
Cannot compile examples (installed from arduinoIDE)

### ISSUE THREAD

**Issue by n-elia** [luisllamasbinaburo/Arduino-Interpolation#3]
Hi, 
I just wanted to point out that the library version downloaded by ArduinoIDE when installing it from the built-in library manager still contains the issue fixed in #2 . Therefore, it doesn't compile.
Bye and thanks for your work!

**Comment by path9263** [comment]
For anyone else wondering how to use this library... until @luisllamasbinaburo tags a new release anyone wanting to use this library can open the InterpolationLib.cpp file and make the changes seen here: 79c5c4596757be7490a6aca50558c81b2283819e (remove the `= 1` and `= true` from the ends of some lines.

**Comment by luisllamasbinaburo** [comment]
v1.0.1 wtih changes from 79c5c4596757be7490a6aca50558c81b2283819e. Thanks to @n-elia and @path9263
