### ISSUE TITLE
Unable to compile on MKR 1010 board

### ISSUE THREAD

**Issue by Javilen** [luisllamasbinaburo/Arduino-Interpolation#5]
Arduino: 1.8.13 (Windows 10), Board: "Arduino MKR WiFi 1010"

C:\Users\jdeas\Documents\Arduino\libraries\InterpolationLib\src\InterpolationLib.cpp:10:114: error: default argument given for parameter 5 of 'static double Interpolation::Step(double*, double*, int, double, double)' [-fpermissive]

 double Interpolation::Step(double xValues[], double yValues[], int numValues, double pointX, double threshold = 1)

                                                                                                                  ^

In file included from C:\Users\jdeas\Documents\Arduino\libraries\InterpolationLib\src\InterpolationLib.cpp:8:0:

C:\Users\jdeas\Documents\Arduino\libraries\InterpolationLib\src\InterpolationLib.h:66:16: note: previous specification in 'static double Interpolation::Step(double*, double*, int, double, double)' here

  static double Step(double xValues[], double yValues[], int numValues, double pointX, double threshold = 1);

                ^~~~

C:\Users\jdeas\Documents\Arduino\libraries\InterpolationLib\src\InterpolationLib.cpp:24:112: error: default argument given for parameter 5 of 'static double Interpolation::Linear(double*, double*, int, double, bool)' [-fpermissive]

 double Interpolation::Linear(double xValues[], double yValues[], int numValues, double pointX, bool trim = true)

                                                                                                                ^

In file included from C:\Users\jdeas\Documents\Arduino\libraries\InterpolationLib\src\InterpolationLib.cpp:8:0:

C:\Users\jdeas\Documents\Arduino\libraries\InterpolationLib\src\InterpolationLib.h:70:16: note: previous specification in 'static double Interpolation::Linear(double*, double*, int, double, bool)' here

  static double Linear(double xValues[], double yValues[], int numValues, double pointX, bool trim = true);

                ^~~~~~

C:\Users\jdeas\Documents\Arduino\libraries\InterpolationLib\src\InterpolationLib.cpp:56:116: error: default argument given for parameter 5 of 'static double Interpolation::SmoothStep(double*, double*, int, double, bool)' [-fpermissive]

 double Interpolation::SmoothStep(double xValues[], double yValues[], int numValues, double pointX, bool trim = true)

                                                                                                                    ^

In file included from C:\Users\jdeas\Documents\Arduino\libraries\InterpolationLib\src\InterpolationLib.cpp:8:0:

C:\Users\jdeas\Documents\Arduino\libraries\InterpolationLib\src\InterpolationLib.h:72:16: note: previous specification in 'static double Interpolation::SmoothStep(double*, double*, int, double, bool)' here

  static double SmoothStep(double xValues[], double yValues[], int numValues, double pointX, bool trim = true);

                ^~~~~~~~~~

C:\Users\jdeas\Documents\Arduino\libraries\InterpolationLib\src\InterpolationLib.cpp:75:119: error: default argument given for parameter 5 of 'static double Interpolation::CatmullSpline(double*, double*, int, double, bool)' [-fpermissive]

 double Interpolation::CatmullSpline(double xValues[], double yValues[], int numValues, double pointX, bool trim = true)

                                                                                                                       ^

In file included from C:\Users\jdeas\Documents\Arduino\libraries\InterpolationLib\src\InterpolationLib.cpp:8:0:

C:\Users\jdeas\Documents\Arduino\libraries\InterpolationLib\src\InterpolationLib.h:73:16: note: previous specification in 'static double Interpolation::CatmullSpline(double*, double*, int, double, bool)' here

  static double CatmullSpline(double xValues[], double yValues[], int numValues, double pointX, bool trim = true);

                ^~~~~~~~~~~~~

C:\Users\jdeas\Documents\Arduino\libraries\InterpolationLib\src\InterpolationLib.cpp:131:123: error: default argument given for parameter 5 of 'static double Interpolation::ConstrainedSpline(double*, double*, int, double, bool)' [-fpermissive]

 double Interpolation::ConstrainedSpline(double xValues[], double yValues[], int numValues, double pointX, bool trim = true)

                                                                                                                           ^

In file included from C:\Users\jdeas\Documents\Arduino\libraries\InterpolationLib\src\InterpolationLib.cpp:8:0:

C:\Users\jdeas\Documents\Arduino\libraries\InterpolationLib\src\InterpolationLib.h:74:16: note: previous specification in 'static double Interpolation::ConstrainedSpline(double*, double*, int, double, bool)' here

  static double ConstrainedSpline(double xValues[], double yValues[], int numValues, double pointX, bool trim = true);

                ^~~~~~~~~~~~~~~~~

exit status 1

Error compiling for board Arduino MKR WiFi 1010.

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by luisllamasbinaburo** [comment]
I have no a MKR WiFI 100, so I can't test it. If you have any solution for that, open a PR. Thanks
