### ISSUE TITLE
library.properties has the wrong version

### ISSUE THREAD

**Issue by DanieleDef** [luisllamasbinaburo/Arduino-Interpolation#8]
The file [library.properties](https://github.com/luisllamasbinaburo/Arduino-Interpolation/blob/master/library.properties) still refers to the version 1.0.0

**Comment by ThorstenKleinSmith** [comment]
And this incorrect version number is included in the 1.0.1 release.

**Comment by luisllamasbinaburo** [comment]
See https://github.com/luisllamasbinaburo/Arduino-Interpolation/issues/10#issuecomment-1892346318
