### ISSUE TITLE
InterpolationLib.h generate an error with Arduino IDE version 2.0

### ISSUE THREAD

**Issue by Erictric** [luisllamasbinaburo/Arduino-Interpolation#9]
I updated the Arduino IDE to 2.0 and the compiler is generating this error, this is obtain by compiling the Interpolation example. It works correctly under Arduino IDE 1.8.19:

c:\Users\emond\OneDrive\Documents\Arduino\libraries\InterpolationLib\src\InterpolationLib.cpp:10:114: error: default argument given for parameter 5 of 'static double Interpolation::Step(double*, double*, int, double, double)' [-fpermissive]
 double Interpolation::Step(double xValues[], double yValues[], int numValues, double pointX, double threshold = 1)
                                                                                                                  ^
In file included from c:\Users\emond\OneDrive\Documents\Arduino\libraries\InterpolationLib\src\InterpolationLib.cpp:8:0:
c:\Users\emond\OneDrive\Documents\Arduino\libraries\InterpolationLib\src\InterpolationLib.h:66:16: note: previous specification in 'static double Interpolation::Step(double*, double*, int, double, double)' here
  static double Step(double xValues[], double yValues[], int numValues, double pointX, double threshold = 1);
                ^
c:\Users\emond\OneDrive\Documents\Arduino\libraries\InterpolationLib\src\InterpolationLib.cpp:24:112: error: default argument given for parameter 5 of 'static double Interpolation::Linear(double*, double*, int, double, bool)' [-fpermissive]
 double Interpolation::Linear(double xValues[], double yValues[], int numValues, double pointX, bool trim = true)
                                                                                                                ^
In file included from c:\Users\emond\OneDrive\Documents\Arduino\libraries\InterpolationLib\src\InterpolationLib.cpp:8:0:
c:\Users\emond\OneDrive\Documents\Arduino\libraries\InterpolationLib\src\InterpolationLib.h:70:16: note: previous specification in 'static double Interpolation::Linear(double*, double*, int, double, bool)' here
  static double Linear(double xValues[], double yValues[], int numValues, double pointX, bool trim = true);
                ^
c:\Users\emond\OneDrive\Documents\Arduino\libraries\InterpolationLib\src\InterpolationLib.cpp:56:116: error: default argument given for parameter 5 of 'static double Interpolation::SmoothStep(double*, double*, int, double, bool)' [-fpermissive]
 double Interpolation::SmoothStep(double xValues[], double yValues[], int numValues, double pointX, bool trim = true)
                                                                                                                    ^
In file included from c:\Users\emond\OneDrive\Documents\Arduino\libraries\InterpolationLib\src\InterpolationLib.cpp:8:0:
c:\Users\emond\OneDrive\Documents\Arduino\libraries\InterpolationLib\src\InterpolationLib.h:72:16: note: previous specification in 'static double Interpolation::SmoothStep(double*, double*, int, double, bool)' here
  static double SmoothStep(double xValues[], double yValues[], int numValues, double pointX, bool trim = true);
                ^
c:\Users\emond\OneDrive\Documents\Arduino\libraries\InterpolationLib\src\InterpolationLib.cpp:75:119: error: default argument given for parameter 5 of 'static double Interpolation::CatmullSpline(double*, double*, int, double, bool)' [-fpermissive]
 double Interpolation::CatmullSpline(double xValues[], double yValues[], int numValues, double pointX, bool trim = true)
                                                                                                                       ^
In file included from c:\Users\emond\OneDrive\Documents\Arduino\libraries\InterpolationLib\src\InterpolationLib.cpp:8:0:
c:\Users\emond\OneDrive\Documents\Arduino\libraries\InterpolationLib\src\InterpolationLib.h:73:16: note: previous specification in 'static double Interpolation::CatmullSpline(double*, double*, int, double, bool)' here
  static double CatmullSpline(double xValues[], double yValues[], int numValues, double pointX, bool trim = true);
                ^
c:\Users\emond\OneDrive\Documents\Arduino\libraries\InterpolationLib\src\InterpolationLib.cpp:131:123: error: default argument given for parameter 5 of 'static double Interpolation::ConstrainedSpline(double*, double*, int, double, bool)' [-fpermissive]
 double Interpolation::ConstrainedSpline(double xValues[], double yValues[], int numValues, double pointX, bool trim = true)
                                                                                                                           ^
In file included from c:\Users\emond\OneDrive\Documents\Arduino\libraries\InterpolationLib\src\InterpolationLib.cpp:8:0:
c:\Users\emond\OneDrive\Documents\Arduino\libraries\InterpolationLib\src\InterpolationLib.h:74:16: note: previous specification in 'static double Interpolation::ConstrainedSpline(double*, double*, int, double, bool)' here
  static double ConstrainedSpline(double xValues[], double yValues[], int numValues, double pointX, bool trim = true);
                ^

exit status 1

Compilation error: exit status 1

**Comment by luisllamasbinaburo** [comment]
See https://github.com/luisllamasbinaburo/Arduino-Interpolation/issues/10#issuecomment-1892346318
